// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParaPharma.Infrastructure.Data;

#nullable disable

namespace ParaPharma.Infrastructure.Migrations.ExamDwh
{
    [DbContext(typeof(ExamDwhContext))]
    partial class ExamDwhContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DimCustomer", b =>
                {
                    b.Property<int>("CustomerKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerKey"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerKey");

                    b.ToTable("DimCustomers");
                });

            modelBuilder.Entity("DimPerson", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessEntityID"));

                    b.Property<int?>("EmailPromotion")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("NameStyle")
                        .HasColumnType("bit");

                    b.Property<string>("PersonType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessEntityID");

                    b.ToTable("DimPersons");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimCreditCard", b =>
                {
                    b.Property<int>("CreditCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreditCardID"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ExpMonth")
                        .HasColumnType("tinyint");

                    b.Property<short>("ExpYear")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CreditCardID");

                    b.ToTable("DimCreditCards");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimProduct", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FinishedGoodsFlag")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("MakeFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductSubcategoryID")
                        .HasColumnType("int");

                    b.Property<short?>("ReorderPoint")
                        .HasColumnType("smallint");

                    b.Property<short?>("SafetyStockLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeUnitMeasureCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("StandardCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeightUnitMeasureCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductSubcategoryID");

                    b.ToTable("DimProduct");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryID"));

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("rowguid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductCategoryID");

                    b.ToTable("DimProductCategory");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimProductSubCategory", b =>
                {
                    b.Property<int>("ProductSubcategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductSubcategoryID"));

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductCategoryID")
                        .HasColumnType("int");

                    b.HasKey("ProductSubcategoryID");

                    b.HasIndex("ProductCategoryID");

                    b.ToTable("DimProductSubCategory");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimSalesPerson", b =>
                {
                    b.Property<int>("SalesPersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesPersonID"));

                    b.Property<decimal?>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CommissionPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalesLastYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalesQuota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalesYTD")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SalesPersonID");

                    b.ToTable("DimSalesPerson");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimSalesTerritory", b =>
                {
                    b.Property<int>("TerritoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerritoryID"));

                    b.Property<decimal?>("CostLastYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostYTD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CountryRegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalesLastYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalesYTD")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TerritoryID");

                    b.ToTable("DimSalesTerritory");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.FactSale", b =>
                {
                    b.Property<int>("SalesOrderID")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderDetailID")
                        .HasColumnType("int");

                    b.Property<string>("CarrierTrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreditCardID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("OrderQty")
                        .HasColumnType("smallint");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<byte>("RevisionNumber")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SalesPersonID")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialOfferID")
                        .HasColumnType("int");

                    b.Property<int?>("TerritoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPriceDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SalesOrderID", "SalesOrderDetailID");

                    b.HasIndex("CreditCardID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SalesPersonID");

                    b.HasIndex("TerritoryID");

                    b.ToTable("FactSale");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimProduct", b =>
                {
                    b.HasOne("ParaPharma.Core.Entities.DWH.DimProductSubCategory", "ProductSubCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductSubcategoryID");

                    b.Navigation("ProductSubCategory");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimProductSubCategory", b =>
                {
                    b.HasOne("ParaPharma.Core.Entities.DWH.DimProductCategory", "ProductCategory")
                        .WithMany("ProductSubCategories")
                        .HasForeignKey("ProductCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.FactSale", b =>
                {
                    b.HasOne("ParaPharma.Core.Entities.DWH.DimCreditCard", "CreditCard")
                        .WithMany("FactSales")
                        .HasForeignKey("CreditCardID");

                    b.HasOne("ParaPharma.Core.Entities.DWH.DimProduct", "Product")
                        .WithMany("FactSales")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParaPharma.Core.Entities.DWH.DimSalesPerson", "SalesPerson")
                        .WithMany("FactSales")
                        .HasForeignKey("SalesPersonID");

                    b.HasOne("ParaPharma.Core.Entities.DWH.DimSalesTerritory", "Territory")
                        .WithMany("FactSales")
                        .HasForeignKey("TerritoryID");

                    b.Navigation("CreditCard");

                    b.Navigation("Product");

                    b.Navigation("SalesPerson");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimCreditCard", b =>
                {
                    b.Navigation("FactSales");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimProduct", b =>
                {
                    b.Navigation("FactSales");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimProductCategory", b =>
                {
                    b.Navigation("ProductSubCategories");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimProductSubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimSalesPerson", b =>
                {
                    b.Navigation("FactSales");
                });

            modelBuilder.Entity("ParaPharma.Core.Entities.DWH.DimSalesTerritory", b =>
                {
                    b.Navigation("FactSales");
                });
#pragma warning restore 612, 618
        }
    }
}
